# Generated by Django 4.0.4 on 2022-05-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_issues_assignee_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.CharField(choices=[('WEB', 'Website'), ('ADR', 'Android'), ('IOS', 'IOS')], max_length=30),
        ),
    ]
