# Generated by Django 4.0.4 on 2022-05-24 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_rename_project_id_contributors_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=120)),
                ('priority', models.CharField(choices=[('LOW', 'Basse priorité...'), ('MID', 'Moyenne priorité.'), ('HIG', 'Haute priorité !')], max_length=20)),
                ('tag', models.CharField(choices=[('LOW', 'Basse priorité...'), ('MID', 'Moyenne priorité.'), ('HIG', 'Haute priorité !')], max_length=10)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('assigne_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_assigne_user', to=settings.AUTH_USER_MODEL)),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_author_user', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects')),
            ],
        ),
    ]
