# Generated by Django 4.0.4 on 2022-05-24 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='tag',
            field=models.CharField(choices=[('BUG', 'Bug'), ('TSK', 'Tâche'), ('UPG', 'Amélioration')], max_length=10),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.issues')),
            ],
        ),
    ]
