# Generated by Django 4.0.4 on 2022-05-27 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_issues_tag_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='author_user_id',
            new_name='author_user',
        ),
    ]
